format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$java\
$ruby\
$package\
$aws\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = "."

[aws]
symbol = '  '
style = 'yellow'
format = '[$symbol($profile )(\[$duration\] )]($style)'
