return {
  "mfussenegger/nvim-dap",
  config = function()
    local dap = require("dap")

    vim.keymap.set("n", "<F5>", function()
      dap.continue()
    end, { desc = "Start/Continue Debugging" })
    vim.keymap.set("n", "<F10>", function()
      dap.step_over()
    end, { desc = "Step Over" })
    vim.keymap.set("n", "<F11>", function()
      dap.step_into()
    end, { desc = "Step Into" })
    vim.keymap.set("n", "<F12>", function()
      dap.step_out()
    end, { desc = "Step Out" })
    vim.keymap.set("n", "<leader>db", function()
      dap.toggle_breakpoint()
    end, { desc = "Toggle Breakpoint" })
    vim.keymap.set("n", "<leader>dB", function()
      dap.set_breakpoint(vim.fn.input("Breakpoint condition: "))
    end, { desc = "Conditional Breakpoint" })
    vim.keymap.set("n", "<leader>dr", function()
      dap.repl.open()
    end, { desc = "Open Debug REPL" })
    vim.keymap.set("n", "<leader>dl", function()
      dap.run_last()
    end, { desc = "Run Last Debugger" })
  end,
}
